/**
 * GET /go/feed — changelog / what's-new entries.
 *
 * Unlike the other /go/* endpoints this one does NOT requireKV — the
 * handler falls back to a bundled feed-data.js (generated by
 * scripts/build-feed.js from CHANGELOG.md) when KV is empty or
 * unbound, so /go/feed is always responsive even before KV ships.
 */

import { getFeed } from '../../_lib/go/feed.js';
import { handlePreflight } from '../../_lib/go/shared.js';

export const onRequestOptions = () => handlePreflight();

export async function onRequestGet({ request, env }) {
  return getFeed(request, env);
}
