// @generated by scripts/build-feed.js — do not edit by hand.
export default {
  "items": [
    {
      "id": "0.2.0",
      "type": "update",
      "title": "v0.2.0",
      "body": "`[data-icon]` icon primitive — a terse, native way to place a single monochrome icon (`<i data-icon=\"star\">`, or on any element) via a CSS `mask` `::before` plus a tiny core-loaded enhancer, alongside `<icon-wc>`. Ships build-generated per-set no-JS stylesheets and name manife…",
      "url": "https://vanilla-breeze.com/changelog#0.2.0",
      "date": "2026-07-02"
    },
    {
      "id": "0.1.0",
      "type": "update",
      "title": "v0.1.0",
      "body": "Initial public release. Tokens — design tokens for spacing, typography, colors, sizing, borders, shadows, motion, and fluid scaling Native element styles — layered CSS for `<nav>`, `<table>`, `<form>`, `<aside>`, `<main>`, `<dialog>`, `<details>`, and more Layout system — `dat…",
      "url": "https://vanilla-breeze.com/changelog#0.1.0",
      "date": "2025-01-01"
    }
  ]
};
