/**
 * 11ty global data: budgetReport
 *
 * Reads dist/cdn/budget-report.json (generated by `npm run budget`)
 * and exposes it as `budgetReport` in templates.
 *
 * Falls back to empty object in dev mode or if file doesn't exist.
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPORT_PATH = join(__dirname, '..', '..', '..', 'dist', 'cdn', 'budget-report.json');

export default function () {
  if (!existsSync(REPORT_PATH)) {
    return { artifacts: {}, totals: {} };
  }

  try {
    return JSON.parse(readFileSync(REPORT_PATH, 'utf-8'));
  } catch {
    return { artifacts: {}, totals: {} };
  }
}
