/**
 * Element Index Data
 *
 * Alphabetical listing of all HTML elements, custom elements, and web components.
 * Used by the elements index page.
 */
const elementsByLetter = {
  A: [
    { name: 'a', type: 'native', href: '/docs/elements/native/a/' },
    { name: 'abbr', type: 'native', href: '/docs/elements/native/abbr/' },
    { name: 'accordion-wc', type: 'component', href: '/docs/elements/web-components/accordion/' },
    { name: 'address', type: 'native', href: '/docs/elements/native/address/' },
    { name: 'area', type: 'native', href: '/docs/elements/native/area/' },
    { name: 'article', type: 'native', href: '/docs/elements/native/article/' },
    { name: 'aside', type: 'native', href: '/docs/elements/native/aside/' },
    { name: 'audio', type: 'native', href: '/docs/elements/native/audio/' },
  ],
  B: [
    { name: 'b', type: 'native', href: '/docs/elements/native/b/' },
    { name: 'base', type: 'native', href: '/docs/elements/native/base/' },
    { name: 'bdi', type: 'native', href: '/docs/elements/native/bdi/' },
    { name: 'bdo', type: 'native', href: '/docs/elements/native/bdo/' },
    { name: 'blockquote', type: 'native', href: '/docs/elements/native/blockquote/' },
    { name: 'body', type: 'native', href: '/docs/elements/native/body/' },
    { name: 'br', type: 'native', href: '/docs/elements/native/br/' },
    { name: 'brand-mark', type: 'custom', href: '/docs/elements/custom-elements/brand-mark/' },
    { name: 'button', type: 'native', href: '/docs/elements/native/button/' },
  ],
  C: [
    { name: 'canvas', type: 'native', href: '/docs/elements/native/canvas/' },
    { name: 'caption', type: 'native', href: '/docs/elements/native/caption/' },
    { name: 'carousel-wc', type: 'component', href: '/docs/elements/web-components/carousel/' },
    { name: 'cite', type: 'native', href: '/docs/elements/native/cite/' },
    { name: 'code', type: 'native', href: '/docs/elements/native/code/' },
    { name: 'col', type: 'native', href: '/docs/elements/native/col/' },
    { name: 'colgroup', type: 'native', href: '/docs/elements/native/colgroup/' },
    { name: 'combobox-wc', type: 'component', href: '/docs/elements/web-components/combobox/' },
    { name: 'comparison-wc', type: 'component', href: '/docs/elements/web-components/comparison/' },
    { name: 'content-swap', type: 'component', href: '/docs/elements/web-components/content-swap/' },
  ],
  D: [
    { name: 'data', type: 'native', href: '/docs/elements/native/data/' },
    { name: 'datalist', type: 'native', href: '/docs/elements/native/datalist/' },
    { name: 'dd', type: 'native', href: '/docs/elements/native/dd/' },
    { name: 'del', type: 'native', href: '/docs/elements/native/del/' },
    { name: 'details', type: 'native', href: '/docs/elements/native/details/' },
    { name: 'dfn', type: 'native', href: '/docs/elements/native/dfn/' },
    { name: 'dialog', type: 'native', href: '/docs/elements/native/dialog/' },
    { name: 'div', type: 'native', href: '/docs/elements/native/div/' },
    { name: 'dl', type: 'native', href: '/docs/elements/native/dl/' },
    { name: 'dl-item', type: 'custom', href: '/docs/elements/custom-elements/dl-item/' },
    { name: 'drag-surface', type: 'component', href: '/docs/elements/web-components/drag-surface/' },
    { name: 'dropdown-wc', type: 'component', href: '/docs/elements/web-components/dropdown/' },
    { name: 'dt', type: 'native', href: '/docs/elements/native/dt/' },
  ],
  E: [
    { name: 'em', type: 'native', href: '/docs/elements/native/em/' },
    { name: 'embed', type: 'native', href: '/docs/elements/native/embed/' },
    { name: 'emoji-picker', type: 'component', href: '/docs/elements/web-components/emoji-picker/' },
  ],
  F: [
    { name: 'fieldset', type: 'native', href: '/docs/elements/native/fieldset/' },
    { name: 'figcaption', type: 'native', href: '/docs/elements/native/figcaption/' },
    { name: 'figure', type: 'native', href: '/docs/elements/native/figure/' },
    { name: 'footer', type: 'native', href: '/docs/elements/native/footer/' },
    { name: 'footnotes-wc', type: 'component', href: '/docs/elements/web-components/footnotes/' },
    { name: 'form', type: 'native', href: '/docs/elements/native/form/' },
    { name: 'form-field', type: 'custom', href: '/docs/elements/custom-elements/form-field/' },
  ],
  G: [
    { name: 'geo-map', type: 'component', href: '/docs/elements/web-components/geo-map/' },
  ],
  H: [
    { name: 'h1', type: 'native', href: '/docs/elements/native/h1/' },
    { name: 'h2', type: 'native', href: '/docs/elements/native/h2/' },
    { name: 'h3', type: 'native', href: '/docs/elements/native/h3/' },
    { name: 'h4', type: 'native', href: '/docs/elements/native/h4/' },
    { name: 'h5', type: 'native', href: '/docs/elements/native/h5/' },
    { name: 'h6', type: 'native', href: '/docs/elements/native/h6/' },
    { name: 'head', type: 'native', href: '/docs/elements/native/head/' },
    { name: 'header', type: 'native', href: '/docs/elements/native/header/' },
    { name: 'heading-links', type: 'component', href: '/docs/elements/web-components/heading-links/' },
    { name: 'hgroup', type: 'native', href: '/docs/elements/native/hgroup/' },
    { name: 'html-include-wc', type: 'component', href: '/docs/elements/web-components/html-include/' },
    { name: 'hr', type: 'native', href: '/docs/elements/native/hr/' },
    { name: 'html', type: 'native', href: '/docs/elements/native/html/' },
  ],
  I: [
    { name: 'i', type: 'native', href: '/docs/elements/native/i/' },
    { name: 'icon-wc', type: 'component', href: '/docs/elements/web-components/icons/' },
    { name: 'iframe', type: 'native', href: '/docs/elements/native/iframe/' },
    { name: 'img', type: 'native', href: '/docs/elements/native/img/' },
    { name: 'input', type: 'native', href: '/docs/elements/native/input/' },
    { name: 'ins', type: 'native', href: '/docs/elements/native/ins/' },
  ],
  K: [
    { name: 'kbd', type: 'native', href: '/docs/elements/native/kbd/' },
  ],
  L: [
    { name: 'label', type: 'native', href: '/docs/elements/native/label/' },
    { name: 'layout-badge', type: 'custom', href: '/docs/elements/custom-elements/layout-badge/' },
    { name: 'layout-card', type: 'custom', href: '/docs/elements/custom-elements/layout-card/' },
    { name: 'layout-center', type: 'custom', href: '/docs/elements/custom-elements/center/' },
    { name: 'layout-cluster', type: 'custom', href: '/docs/elements/custom-elements/cluster/' },
    { name: 'layout-cover', type: 'custom', href: '/docs/elements/custom-elements/cover/' },
    { name: 'layout-grid', type: 'custom', href: '/docs/elements/custom-elements/grid/' },
    { name: 'layout-imposter', type: 'custom', href: '/docs/elements/custom-elements/imposter/' },
    { name: 'layout-reel', type: 'custom', href: '/docs/elements/custom-elements/reel/' },
    { name: 'layout-sidebar', type: 'custom', href: '/docs/elements/custom-elements/sidebar/' },
    { name: 'layout-stack', type: 'custom', href: '/docs/elements/custom-elements/stack/' },
    { name: 'layout-switcher', type: 'custom', href: '/docs/elements/custom-elements/switcher/' },
    { name: 'layout-text', type: 'custom', href: '/docs/elements/custom-elements/layout-text/' },
    { name: 'legend', type: 'native', href: '/docs/elements/native/legend/' },
    { name: 'li', type: 'native', href: '/docs/elements/native/li/' },
    { name: 'link', type: 'native', href: '/docs/elements/native/link/' },
    { name: 'loading-spinner', type: 'custom', href: '/docs/elements/custom-elements/loading-spinner/' },
  ],
  M: [
    { name: 'main', type: 'native', href: '/docs/elements/native/main/' },
    { name: 'map', type: 'native', href: '/docs/elements/native/map/' },
    { name: 'mark', type: 'native', href: '/docs/elements/native/mark/' },
    { name: 'math', type: 'native', href: '/docs/elements/native/math/' },
    { name: 'menu', type: 'native', href: '/docs/elements/native/menu/' },
    { name: 'meta', type: 'native', href: '/docs/elements/native/meta/' },
    { name: 'meter', type: 'native', href: '/docs/elements/native/meter/' },
  ],
  N: [
    { name: 'nav', type: 'native', href: '/docs/elements/native/nav/' },
    { name: 'noscript', type: 'native', href: '/docs/elements/native/noscript/' },
  ],
  O: [
    { name: 'object', type: 'native', href: '/docs/elements/native/object/' },
    { name: 'ol', type: 'native', href: '/docs/elements/native/ol/' },
    { name: 'optgroup', type: 'native', href: '/docs/elements/native/optgroup/' },
    { name: 'option', type: 'native', href: '/docs/elements/native/option/' },
    { name: 'output', type: 'native', href: '/docs/elements/native/output/' },
  ],
  P: [
    { name: 'p', type: 'native', href: '/docs/elements/native/p/' },
    { name: 'page-toc', type: 'component', href: '/docs/elements/web-components/page-toc/' },
    { name: 'picture', type: 'native', href: '/docs/elements/native/picture/' },
    { name: 'pre', type: 'native', href: '/docs/elements/native/pre/' },
    { name: 'progress', type: 'native', href: '/docs/elements/native/progress/' },
    { name: 'progress-ring', type: 'custom', href: '/docs/elements/custom-elements/progress-ring/' },
  ],
  Q: [
    { name: 'q', type: 'native', href: '/docs/elements/native/q/' },
    { name: 'qr-code', type: 'component', href: '/docs/elements/web-components/qr-code/' },
  ],
  R: [
    { name: 'rating-wc', type: 'component', href: '/docs/elements/web-components/rating/' },
    { name: 'rp', type: 'native', href: '/docs/elements/native/rp/' },
    { name: 'rt', type: 'native', href: '/docs/elements/native/rt/' },
    { name: 'ruby', type: 'native', href: '/docs/elements/native/ruby/' },
  ],
  S: [
    { name: 's', type: 'native', href: '/docs/elements/native/s/' },
    { name: 'samp', type: 'native', href: '/docs/elements/native/samp/' },
    { name: 'script', type: 'native', href: '/docs/elements/native/script/' },
    { name: 'search', type: 'native', href: '/docs/elements/native/search/' },
    { name: 'search-wc', type: 'component', href: '/docs/elements/web-components/search-wc/' },
    { name: 'section', type: 'native', href: '/docs/elements/native/section/' },
    { name: 'select', type: 'native', href: '/docs/elements/native/select/' },
    { name: 'shortcuts-wc', type: 'component', href: '/docs/elements/web-components/shortcuts/' },
    { name: 'slide-accept-wc', type: 'component', href: '/docs/elements/web-components/slide-accept/' },
    { name: 'slot', type: 'native', href: '/docs/elements/native/slot/' },
    { name: 'small', type: 'native', href: '/docs/elements/native/small/' },
    { name: 'source', type: 'native', href: '/docs/elements/native/source/' },
    { name: 'span', type: 'native', href: '/docs/elements/native/span/' },
    { name: 'splitter-wc', type: 'component', href: '/docs/elements/web-components/splitter/' },
    { name: 'status-message', type: 'custom', href: '/docs/elements/custom-elements/status-message/' },
    { name: 'strong', type: 'native', href: '/docs/elements/native/strong/' },
    { name: 'style', type: 'native', href: '/docs/elements/native/style/' },
    { name: 'sub', type: 'native', href: '/docs/elements/native/sub/' },
    { name: 'summary', type: 'native', href: '/docs/elements/native/summary/' },
    { name: 'sup', type: 'native', href: '/docs/elements/native/sup/' },
    { name: 'svg', type: 'native', href: '/docs/elements/native/svg/' },
  ],
  T: [
    { name: 'table', type: 'native', href: '/docs/elements/native/table/' },
    { name: 'table-wc', type: 'component', href: '/docs/elements/web-components/table-wc/' },
    { name: 'tabs-wc', type: 'component', href: '/docs/elements/web-components/tabs/' },
    { name: 'tbody', type: 'native', href: '/docs/elements/native/tbody/' },
    { name: 'td', type: 'native', href: '/docs/elements/native/td/' },
    { name: 'template', type: 'native', href: '/docs/elements/native/template/' },
    { name: 'text-divider', type: 'custom', href: '/docs/elements/custom-elements/text-divider/' },
    { name: 'textarea', type: 'native', href: '/docs/elements/native/textarea/' },
    { name: 'tfoot', type: 'native', href: '/docs/elements/native/tfoot/' },
    { name: 'th', type: 'native', href: '/docs/elements/native/th/' },
    { name: 'thead', type: 'native', href: '/docs/elements/native/thead/' },
    { name: 'theme-wc', type: 'component', href: '/docs/elements/web-components/theme-wc/' },
    { name: 'time', type: 'native', href: '/docs/elements/native/time/' },
    { name: 'title', type: 'native', href: '/docs/elements/native/title/' },
    { name: 'toast-wc', type: 'component', href: '/docs/elements/web-components/toast/' },
    { name: 'tooltip-wc', type: 'component', href: '/docs/elements/web-components/tooltip/' },
    { name: 'tr', type: 'native', href: '/docs/elements/native/tr/' },
    { name: 'track', type: 'native', href: '/docs/elements/native/track/' },
  ],
  U: [
    { name: 'u', type: 'native', href: '/docs/elements/native/u/' },
    { name: 'ul', type: 'native', href: '/docs/elements/native/ul/' },
    { name: 'user-avatar', type: 'custom', href: '/docs/elements/custom-elements/user-avatar/' },
  ],
  V: [
    { name: 'var', type: 'native', href: '/docs/elements/native/var/' },
    { name: 'video', type: 'native', href: '/docs/elements/native/video/' },
  ],
  W: [
    { name: 'wbr', type: 'native', href: '/docs/elements/native/wbr/' },
  ],
};

// Calculate stats
const allElements = Object.values(elementsByLetter).flat();

export default {
  byLetter: elementsByLetter,
  nativeCount: allElements.filter(e => e.type === 'native').length,
  customCount: allElements.filter(e => e.type === 'custom').length,
  componentCount: allElements.filter(e => e.type === 'component').length,
  totalCount: allElements.length,
};
