/**
 * Theme Registry — Single source of truth for all VB themes.
 *
 * Used by: Color Schemer presets, Theme Lab hints, Theme Composer starting points,
 *          theme-wc swatch data, and the /docs/tools/ index page.
 *
 * Categories:
 *   color        — Override hue values only (ocean, forest, sunset, etc.)
 *   personality   — Comprehensive design systems (modern, minimal, classic)
 *   extreme       — Dramatic visual transformations (swiss, brutalist, cyber, etc.)
 *   accessibility — Functional WCAG themes (composable with decorative themes)
 */

export default [
  // ─── Default ───────────────────────────────────────────────
  {
    id: 'default',
    name: 'Default',
    category: 'color',
    character: 'The VB default — balanced blue-purple palette',
    colors: { huePrimary: 260, hueSecondary: 200, hueAccent: 30 },
    swatchBg: '#3b82f6',
    swatchFg: '#fff',
  },

  // ─── Color Themes ──────────────────────────────────────────
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'color',
    character: 'Cool oceanic blues with teal undertones',
    colors: { huePrimary: 200, hueSecondary: 180, hueAccent: 45 },
    swatchBg: '#0891b2',
    swatchFg: '#fff',
  },
  {
    id: 'forest',
    name: 'Forest',
    category: 'color',
    character: 'Natural earthy greens with amber accent',
    colors: { huePrimary: 145, hueSecondary: 90, hueAccent: 30 },
    swatchBg: '#059669',
    swatchFg: '#fff',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'color',
    character: 'Warm energetic orange-red palette',
    colors: { huePrimary: 25, hueSecondary: 0, hueAccent: 280 },
    swatchBg: '#ea580c',
    swatchFg: '#fff',
  },
  {
    id: 'rose',
    name: 'Rose',
    category: 'color',
    character: 'Warm romantic pinks with ocean accent',
    colors: { huePrimary: 350, hueSecondary: 330, hueAccent: 200 },
    swatchBg: '#e11d48',
    swatchFg: '#fff',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'color',
    character: 'Soft calming purples with golden accent',
    colors: { huePrimary: 280, hueSecondary: 300, hueAccent: 60 },
    swatchBg: '#a855f7',
    swatchFg: '#fff',
  },
  {
    id: 'coral',
    name: 'Coral',
    category: 'color',
    character: 'Warm peachy tones with teal contrast',
    colors: { huePrimary: 15, hueSecondary: 25, hueAccent: 180 },
    swatchBg: '#f97316',
    swatchFg: '#fff',
  },
  {
    id: 'slate',
    name: 'Slate',
    category: 'color',
    character: 'Cool professional gray-blue palette',
    colors: { huePrimary: 220, hueSecondary: 210, hueAccent: 45 },
    swatchBg: '#64748b',
    swatchFg: '#fff',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    category: 'color',
    character: 'Rich vibrant green with warm accent',
    colors: { huePrimary: 160, hueSecondary: 140, hueAccent: 30 },
    swatchBg: '#10b981',
    swatchFg: '#fff',
  },
  {
    id: 'amber',
    name: 'Amber',
    category: 'color',
    character: 'Golden warm tones with cool contrast',
    colors: { huePrimary: 45, hueSecondary: 30, hueAccent: 240 },
    swatchBg: '#f59e0b',
    swatchFg: '#fff',
  },
  {
    id: 'indigo',
    name: 'Indigo',
    category: 'color',
    character: 'Deep rich blues with violet depth',
    colors: { huePrimary: 250, hueSecondary: 270, hueAccent: 35 },
    swatchBg: '#6366f1',
    swatchFg: '#fff',
  },

  // ─── Personality Themes ────────────────────────────────────
  {
    id: 'modern',
    name: 'Modern',
    category: 'personality',
    character: 'Vibrant & elevated — tech-forward with bounce',
    colors: { huePrimary: 270, hueSecondary: 220, hueAccent: 45, primaryL: 0.55, primaryC: 0.22 },
    swatchBg: '#6366f1',
    swatchFg: '#fff',
    typography: { fontSans: "'Inter', system-ui, sans-serif" },
    shape: { radiusPreset: 'rounded' },
    shadows: { preset: 'elevated' },
    motion: { easingPreset: 'bouncy', durationScale: null },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'personality',
    character: 'Clean & flat — content-focused restraint',
    colors: { huePrimary: 240, hueSecondary: 240, hueAccent: 210, primaryC: 0.08 },
    swatchBg: '#71717a',
    swatchFg: '#fff',
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'subtle' },
    motion: { durationScale: null, easingPreset: null },
  },
  {
    id: 'classic',
    name: 'Classic',
    category: 'personality',
    character: 'Serif & elegant — timeless editorial feel',
    colors: { huePrimary: 220, hueSecondary: 200, hueAccent: 35 },
    swatchBg: '#92400e',
    swatchFg: '#fff',
    typography: { fontSerif: "Georgia, 'Times New Roman', serif" },
    shape: { radiusPreset: 'subtle' },
    shadows: { preset: 'default' },
    motion: { durationScale: null, easingPreset: null },
  },

  // ─── Extreme Themes ────────────────────────────────────────
  {
    id: 'swiss',
    name: 'Swiss',
    category: 'extreme',
    character: 'Precision grid typography with Swiss red',
    colors: {},
    swatchBg: '#ff3e00',
    swatchFg: '#fff',
    hints: { borderStyle: 'sharp', iconSet: 'lucide' },
    typography: { fontSans: "'Helvetica Neue', Helvetica, Arial, sans-serif" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'none' },
    motion: { durationScale: 0.75, easingPreset: 'default' },
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    category: 'extreme',
    character: 'Raw industrial — monospace, hard shadows',
    colors: {},
    swatchBg: '#1a1a1a',
    swatchFg: '#f5f5f5',
    hints: { borderStyle: 'rough', iconSet: 'bold' },
    typography: { fontSans: "'Courier New', Courier, monospace" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'hard' },
    motion: { durationScale: 0, easingPreset: 'linear' },
  },
  {
    id: 'cyber',
    name: 'Cyber',
    category: 'extreme',
    character: 'Neon futuristic — glowing UI on dark void',
    colors: { huePrimary: 180, hueAccent: 330 },
    swatchBg: '#0a0a1a',
    swatchFg: '#00ff88',
    hints: { borderStyle: 'neon', iconSet: 'phosphor' },
    typography: { fontSans: "'JetBrains Mono', monospace" },
    shape: { radiusPreset: 'subtle' },
    shadows: { preset: 'none' },
    motion: { durationScale: 1.5, easingPreset: 'default' },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'extreme',
    character: 'Retro CRT — green phosphor on black',
    colors: { huePrimary: 145, hueAccent: 60 },
    swatchBg: '#0d1117',
    swatchFg: '#00ff00',
    hints: { borderStyle: 'sharp', iconSet: 'lucide' },
    typography: { fontSans: "ui-monospace, 'Cascadia Code', monospace" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'none' },
    motion: { durationScale: 0.5, easingPreset: 'linear' },
  },
  {
    id: 'organic',
    name: 'Organic',
    category: 'extreme',
    character: 'Natural handcrafted — warm earthy curves',
    colors: { huePrimary: 60, hueSecondary: 145, hueAccent: 25 },
    swatchBg: '#2d5016',
    swatchFg: '#faf5e6',
    hints: { borderStyle: 'organic', iconSet: 'mage' },
    typography: { fontSerif: "'Lora', Georgia, serif" },
    shape: { radiusPreset: 'rounded' },
    shadows: { preset: 'subtle' },
    motion: { durationScale: 1.5, easingPreset: 'bouncy' },
  },
  {
    id: 'editorial',
    name: 'Editorial',
    category: 'extreme',
    character: 'Magazine elegance — serif hierarchy, thin rules',
    colors: {},
    swatchBg: '#1a1a1a',
    swatchFg: '#c9a227',
    hints: { borderStyle: 'sharp', iconSet: 'lucide' },
    typography: { fontSerif: "'Playfair Display', Georgia, serif" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'none' },
    motion: { durationScale: 1, easingPreset: 'default' },
  },
  {
    id: 'kawaii',
    name: 'Kawaii',
    category: 'extreme',
    character: 'Cute aesthetic — pastel pink, bouncy pills',
    colors: { huePrimary: 350, hueAccent: 180 },
    swatchBg: '#ffb7c5',
    swatchFg: '#ff69b4',
    hints: { borderStyle: 'kawaii', iconSet: 'mage' },
    typography: { fontSans: "'Nunito', 'Quicksand', system-ui, sans-serif" },
    shape: { radiusPreset: 'pill' },
    shadows: { preset: 'elevated' },
    motion: { durationScale: 1.5, easingPreset: 'bouncy' },
  },
  {
    id: '8bit',
    name: '8-Bit',
    category: 'extreme',
    character: 'Retro pixel art — chunky blocks, CRT glow',
    colors: { huePrimary: 145 },
    swatchBg: '#000080',
    swatchFg: '#ffff00',
    hints: { borderStyle: 'pixel', iconSet: 'bold' },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'none' },
    motion: { durationScale: 0, easingPreset: 'linear' },
  },
  {
    id: 'nes',
    name: 'NES',
    category: 'extreme',
    character: 'Console pixels — 4-color palette, beveled frames',
    colors: {},
    swatchBg: '#bcbcbc',
    swatchFg: '#e40521',
    hints: { borderStyle: 'pixel', iconSet: 'bold' },
    typography: { fontSans: "'Press Start 2P', monospace" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'none' },
    motion: { durationScale: 0, easingPreset: 'linear' },
  },
  {
    id: 'win9x',
    name: 'Win9x',
    category: 'extreme',
    character: 'Classic desktop — 3D bevels, system gray',
    colors: { huePrimary: 250 },
    swatchBg: '#008080',
    swatchFg: '#c0c0c0',
    hints: { borderStyle: 'sharp', iconSet: 'lucide' },
    typography: { fontSans: "Tahoma, Arial, sans-serif" },
    shape: { radiusPreset: 'none' },
    shadows: { preset: 'default' },
    motion: { durationScale: 0, easingPreset: 'linear' },
  },

  // ─── Accessibility Themes ─────────────────────────────────
  {
    id: 'a11y-high-contrast',
    name: 'High Contrast',
    category: 'accessibility',
    character: 'AAA contrast (7:1+) for low vision',
    colors: {},
    swatchBg: '#000',
    swatchFg: '#fff',
  },
  {
    id: 'a11y-large-text',
    name: 'Large Text',
    category: 'accessibility',
    character: '25% larger fonts and spacing',
    colors: {},
    swatchBg: '#3b82f6',
    swatchFg: '#fff',
  },
  {
    id: 'a11y-dyslexia',
    name: 'Dyslexia-Friendly',
    category: 'accessibility',
    character: 'Atkinson Hyperlegible with wide spacing',
    colors: {},
    swatchBg: '#3b82f6',
    swatchFg: '#fff',
  },
];
