export default [
  { name: 'accordion-wc', href: '/docs/elements/web-components/accordion/', desc: 'Collapsible content sections' },
  { name: 'carousel-wc', href: '/docs/elements/web-components/carousel/', desc: 'Scroll carousel with controls and autoplay' },
  { name: 'combobox-wc', href: '/docs/elements/web-components/combobox/', desc: 'Autocomplete combobox with form association' },
  { name: 'command-wc', href: '/docs/elements/web-components/command-palette/', desc: 'Cmd+K command palette with search and actions' },
  { name: 'context-menu-wc', href: '/docs/elements/web-components/context-menu/', desc: 'Right-click context menu with keyboard navigation' },
  { name: 'dropdown-wc', href: '/docs/elements/web-components/dropdown/', desc: 'Dropdown menu with keyboard navigation' },
  { name: 'tabs-wc', href: '/docs/elements/web-components/tabs/', desc: 'Tabbed interface component' },
  { name: 'toast-wc', href: '/docs/elements/web-components/toast/', desc: 'Non-blocking notifications' },
  { name: 'tooltip-wc', href: '/docs/elements/web-components/tooltip/', desc: 'Contextual tooltips' },
  { name: 'footnotes-wc', href: '/docs/elements/web-components/footnotes/', desc: 'Inline footnotes with popup' },
  { name: 'geo-map', href: '/docs/elements/web-components/geo-map/', desc: 'Static map tiles with marker and address caption' },
  { name: 'heading-links', href: '/docs/elements/web-components/heading-links/', desc: 'Auto-generate heading anchors' },
  { name: 'icon-wc', href: '/docs/elements/web-components/icons/', desc: 'Icon component with Lucide icons' },
  { name: 'page-toc', href: '/docs/elements/web-components/page-toc/', desc: 'Table of contents generator' },
  { name: 'search-wc', href: '/docs/elements/web-components/search-wc/', desc: 'Search dialog component' },
  { name: 'splitter-wc', href: '/docs/elements/web-components/splitter/', desc: 'Resizable panel splitter with drag divider' },
  { name: 'table-wc', href: '/docs/elements/web-components/table-wc/', desc: 'Enhanced data tables' },
  { name: 'theme-wc', href: '/docs/elements/web-components/theme-wc/', desc: 'Theme picker component' },
];
