#!/usr/bin/env node
/**
 * Parse CHANGELOG.md → emit dist/feed.json in the /go/feed contract shape.
 *
 * Section grammar expected:
 *   ## [{version}] - {date}
 *   {one or more paragraphs / bullet lists describing the release}
 *
 *   ### Added | Changed | Fixed | Removed
 *   - bullet
 *   - bullet
 *
 * Output (per /docs/concepts/service-contracts/ §/go/feed):
 *   {
 *     items: [
 *       { id, type: "update", title, body, url, date }
 *     ]
 *   }
 *
 * Usage:
 *   node scripts/build-feed.js
 *   node scripts/build-feed.js --in CHANGELOG.md --out dist/feed.json --site-url https://vanilla-breeze.com
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    if (flag.startsWith('--')) {
      const key = flag.slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
      out[key] = value;
    }
  }
  return out;
}

const args = parseArgs(process.argv.slice(2));
const REPO = resolve(import.meta.dirname, '..');
const inPath = resolve(REPO, args.in ?? 'CHANGELOG.md');
const outPath = resolve(REPO, args.out ?? 'dist/feed.json');
const siteUrl = args['site-url'] ?? 'https://vanilla-breeze.com';
// Also emit an ESM data module the Pages Function imports for KV-empty
// fallback. Skip with --skip-fn-data.
const fnDataPath = args['skip-fn-data']
  ? null
  : resolve(REPO, 'functions/_lib/go/feed-data.js');

const md = readFileSync(inPath, 'utf-8');

/**
 * Split the markdown into release sections. Each section starts at a
 * `## [version] - date` header.
 */
function parseReleases(text) {
  const lines = text.split('\n');
  /** @type {Array<{version: string, rawDate: string, bodyLines: string[]}>} */
  const releases = [];
  /** @type {{version: string, rawDate: string, bodyLines: string[]} | null} */
  let current = null;

  for (const line of lines) {
    const header = /^##\s+\[([^\]]+)\]\s*-\s*(.+?)\s*$/.exec(line);
    if (header) {
      if (current) releases.push(current);
      current = {
        version: header[1].trim(),
        rawDate: header[2].trim(),
        bodyLines: [],
      };
      continue;
    }
    if (current) current.bodyLines.push(line);
  }
  if (current) releases.push(current);

  return releases;
}

/**
 * Normalize the raw date string to ISO 8601 YYYY-MM-DD when we can parse
 * it. Fall back to the literal value (e.g. "2025") if it isn't a date.
 */
function normalizeDate(raw) {
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;
  const parsed = Date.parse(raw);
  if (!Number.isNaN(parsed)) return new Date(parsed).toISOString().slice(0, 10);
  // Year-only is fine — emit YYYY-01-01 so consumers have a parseable date,
  // but keep the human label in title.
  if (/^\d{4}$/.test(raw)) return `${raw}-01-01`;
  return raw;
}

/**
 * Squash the release body into a one-paragraph summary suitable for a
 * notification body. Strip markdown bullets/headers, trim whitespace, and
 * cap at ~280 chars so it reads cleanly in a panel row.
 */
function summarize(bodyLines) {
  const stripped = bodyLines
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#'))
    .map((l) => l.replace(/^[-*]\s+/, '').replace(/\*\*([^*]+)\*\*/g, '$1'));
  const joined = stripped.join(' ').replace(/\s+/g, ' ').trim();
  return joined.length > 280 ? `${joined.slice(0, 277).trimEnd()}…` : joined;
}

const releases = parseReleases(md);
const items = releases.map((r) => ({
  id: r.version,
  type: 'update',
  title: `v${r.version}`,
  body: summarize(r.bodyLines),
  url: `${siteUrl.replace(/\/$/, '')}/changelog#${r.version.replace(/[^\w.-]/g, '')}`,
  date: normalizeDate(r.rawDate),
}));

const payload = { items };

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n');
console.log(`build-feed: wrote ${items.length} entr${items.length === 1 ? 'y' : 'ies'} → ${outPath.replace(REPO + '/', '')}`);

if (fnDataPath) {
  mkdirSync(dirname(fnDataPath), { recursive: true });
  writeFileSync(
    fnDataPath,
    `// @generated by scripts/build-feed.js — do not edit by hand.\n` +
      `export default ${JSON.stringify(payload, null, 2)};\n`,
  );
  console.log(`build-feed: wrote function-data fallback → ${fnDataPath.replace(REPO + '/', '')}`);
}
